import 'dart:async';
import 'package:flutter/material.dart';
import 'config/app_config.dart';
import 'services/api_client.dart';
import 'services/llm_client.dart';
import 'services/secure_keys.dart';

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); final config=await AppConfig.load(); runApp(GptApp(config:config)); }
class GptApp extends StatelessWidget { const GptApp({super.key,required this.config}); final AppConfig config; @override Widget build(BuildContext c)=>MaterialApp(title:config.name,debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:_color(config.primaryColor),useMaterial3:true),home:HomePage(config:config)); }
Color _color(String v){final h=v.replaceFirst('#','');return Color(int.parse(h.length==6?'FF$h':h,radix:16));}
class MaterialItem { MaterialItem(this.id,this.name,this.text); final int id; final String name; final String text; }
class HomePage extends StatefulWidget { const HomePage({super.key,required this.config}); final AppConfig config; @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage> {
 final userId='local-user'; late final ApiClient api=ApiClient(widget.config.backendBaseUrl); int tab=0; double coins=0; List<MaterialItem> materials=[]; List<dynamic> topics=[]; String provider='openai';
 @override void initState(){super.initState();provider=widget.config.providers.first;_refresh();}
 Future<void> _refresh() async {try{final c=await api.wallet(userId);final t=await api.topics(userId);if(mounted)setState((){coins=c;topics=t;});}catch(_){}}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.config.name),actions:[Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Center(child:Text('${coins.toStringAsFixed(0)} ${widget.config.currencyName}'))),IconButton(onPressed:()=>_keys(c),icon:const Icon(Icons.key_outlined))]),body:IndexedStack(index:tab,children:[_Dashboard(coins:coins,currency:widget.config.currencyName,topics:topics,onRefresh:_refresh),_Materials(materials:materials,onAdd:_addMaterial),_Practice(config:widget.config,api:api,userId:userId,materials:materials,provider:provider,onResult:_refresh),_Boss(config:widget.config,api:api,userId:userId,materials:materials,topics:topics,provider:provider,onResult:_refresh),_Shop(api:api,userId:userId,onResult:_refresh)]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.library_books_outlined),selectedIcon:Icon(Icons.library_books),label:'Materials'),NavigationDestination(icon:Icon(Icons.quiz_outlined),selectedIcon:Icon(Icons.quiz),label:'Practice'),NavigationDestination(icon:Icon(Icons.shield_outlined),selectedIcon:Icon(Icons.shield),label:'Boss'),NavigationDestination(icon:Icon(Icons.shopping_bag_outlined),selectedIcon:Icon(Icons.shopping_bag),label:'Shop')]);
 Future<void> _addMaterial(String name,String text) async {try{final r=await api.uploadText(userId,text);setState(()=>materials.add(MaterialItem(r['id'] as int,name,text)));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
 void _keys(BuildContext c)=>showDialog(context:c,builder:(_)=>_KeyDialog(config:widget.config,initial:provider,onSaved:(p)=>setState(()=>provider=p)));
}
class _Dashboard extends StatelessWidget { const _Dashboard({required this.coins,required this.currency,required this.topics,required this.onRefresh}); final double coins;final String currency;final List<dynamic> topics;final Future<void> Function() onRefresh; @override Widget build(BuildContext c)=>RefreshIndicator(onRefresh:onRefresh,child:ListView(padding:const EdgeInsets.all(20),children:[Text('Ready to study?',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('Adaptive difficulty targets 70–80% accuracy. Correct answers earn coins; harder calibrated problems pay more.'),const SizedBox(height:24),Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet),title:Text('${coins.toStringAsFixed(0)} $currency'),subtitle:const Text('Balance decays gradually after inactivity.'))),const SizedBox(height:16),Text('Topics',style:Theme.of(c).textTheme.titleLarge),if(topics.isEmpty)const ListTile(title:Text('No topics yet'),subtitle:Text('Generate a problem to create one.')),...topics.map((t)=>ListTile(title:Text(t['name']),subtitle:Text('Accuracy ${(t['accuracy']*100).round()}% • Difficulty ${(t['difficulty']*100).round()}% • ${t['attempts']} attempts'),trailing:SizedBox(width:90,child:LinearProgressIndicator(value:(t['accuracy'] as num).toDouble()))))])); }
class _Materials extends StatelessWidget { const _Materials({required this.materials,required this.onAdd}); final List<MaterialItem> materials;final Future<void> Function(String,String) onAdd; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[Text('Study materials',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:8),const Text('Text-layer PDFs are supported by the backend; OCR and image input remain disabled.'),const SizedBox(height:24),FilledButton.icon(onPressed:()=>_paste(c),icon:const Icon(Icons.text_fields),label:const Text('Paste text')),const SizedBox(height:16),...materials.map((m)=>Card(child:ListTile(leading:const Icon(Icons.description),title:Text(m.name),subtitle:Text('${m.text.length} characters'))))]); Future<void> _paste(BuildContext c) async {final n=TextEditingController(text:'Study material');final x=TextEditingController();await showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Add material'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:x,minLines:6,maxLines:12,decoration:const InputDecoration(labelText:'Text'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:(){if(x.text.trim().isNotEmpty){onAdd(n.text.trim().isEmpty?'Material':n.text.trim(),x.text);Navigator.pop(c);}},child:const Text('Add'))]));}}
class _Practice extends StatefulWidget { const _Practice({required this.config,required this.api,required this.userId,required this.materials,required this.provider,required this.onResult}); final AppConfig config;final ApiClient api;final String userId;final List<MaterialItem> materials;final String provider;final Future<void> Function() onResult; @override State<_Practice> createState()=>_PracticeState(); }
class _PracticeState extends State<_Practice> {String topic='General';MaterialItem? material;Map<String,dynamic>? problem;final answer=TextEditingController();DateTime? started;bool busy=false;String status='';
 Future<void> generate() async {if(widget.materials.isEmpty){setState(()=>status='Add material first.');return;}setState(()=>busy=true);try{material=widget.materials.first;final mastery=(await widget.api.topics(widget.userId)).where((x)=>x['name']==topic).toList();final d=mastery.isEmpty ? .5 : (mastery.first['difficulty'] as num).toDouble();final key=await SecureKeys.readLlmApiKey(widget.provider);if(key==null||key.isEmpty)throw Exception('Set your ${widget.provider} API key first.');final llm=LlmClient(provider:widget.provider,model:widget.config.modelFor(widget.provider),apiKey:key);final p=await llm.generateAndSubmit(api:widget.api,userId:widget.userId,materialId:material!.id,material:material!.text,topic:topic,difficulty:d,battleId:null);setState((){problem=p;answer.clear();started=DateTime.now();status='';});}catch(e){setState(()=>status='$e');}finally{setState(()=>busy=false);}}
 Future<void> submit() async {if(problem==null)return;final elapsed=DateTime.now().difference(started!).inMilliseconds;setState(()=>busy=true);try{final r=await widget.api.recordAttempt(userId:widget.userId,problemId:problem!['id'],answer:answer.text,elapsedMs:elapsed);setState(()=>status=r['correct']==true?'Correct. +${r['coins_earned']} coins':'Incorrect.');problem=null;await widget.onResult();_quietNudge();}catch(e){setState(()=>status='$e');}finally{setState(()=>busy=false);}}
 void _quietNudge(){final h=DateTime.now().hour;if((h>=22||h<6)&&mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('You have been studying for a while. Consider taking a natural break.'),duration:Duration(seconds:4)));}
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[Text('Practice',style:Theme.of(c).textTheme.headlineSmall),TextField(decoration:const InputDecoration(labelText:'Topic'),onChanged:(v)=>topic=v),const SizedBox(height:12),FilledButton(onPressed:busy?null:generate,child:Text(busy?'Working…':'Generate problem')),if(problem!=null)Card(margin:const EdgeInsets.only(top:24),child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(problem!['prompt']),const SizedBox(height:16),TextField(controller:answer,decoration:const InputDecoration(labelText:'Your answer')),const SizedBox(height:12),FilledButton(onPressed:busy?null:submit,child:const Text('Submit answer'))])),if(status.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:Text(status))];}
class _Boss extends StatefulWidget { const _Boss({required this.config,required this.api,required this.userId,required this.materials,required this.topics,required this.provider,required this.onResult}); final AppConfig config;final ApiClient api;final String userId;final List<MaterialItem> materials;final List<dynamic> topics;final String provider;final Future<void> Function() onResult; @override State<_Boss> createState()=>_BossState(); }
class _BossState extends State<_Boss> {int? battleId;Map<String,dynamic>? problem;DateTime? started;String status='';bool busy=false;int? topicId;double hp=100;final answer=TextEditingController();
 Future<void> start() async {if(topicId==null||widget.materials.isEmpty){setState(()=>status='Choose a topic and add material.');return;}try{final b=await widget.api.startBoss(widget.userId,topicId!);setState((){battleId=b['id'];hp=(b['boss_hp'] as num).toDouble();status='Boss battle started.';});}catch(e){setState(()=>status='$e');}}
 Future<void> turn() async {if(battleId==null)return;final t=widget.topics.firstWhere((x)=>x['id']==topicId);final d=(((t['difficulty'] as num).toDouble()+.05).clamp(0.0,1.0) as num).toDouble();final key=await SecureKeys.readLlmApiKey(widget.provider);if(key==null)throw Exception('Set your API key first.');setState(()=>busy=true);try{final llm=LlmClient(provider:widget.provider,model:widget.config.modelFor(widget.provider),apiKey:key);final p=await llm.generateAndSubmit(api:widget.api,userId:widget.userId,materialId:widget.materials.first.id,material:widget.materials.first.text,topic:t['name'],difficulty:d,battleId:battleId);setState((){problem=p;started=DateTime.now();});}catch(e){setState(()=>status='$e');}finally{setState(()=>busy=false);}}
 Future<void> attack() async {if(problem==null||battleId==null)return;setState(()=>busy=true);try{final r=await widget.api.recordAttempt(userId:widget.userId,problemId:problem!['id'],answer:answer.text,elapsedMs:DateTime.now().difference(started!).inMilliseconds,battleId:battleId);setState((){hp=(r['boss_hp'] as num?)?.toDouble()??hp;status=r['battle_outcome']=='win'?'Boss defeated.':'${r['correct']==true?'Hit':'Miss'} — ${hp.toStringAsFixed(0)} HP remaining';problem=null;});if(r['battle_outcome']=='win'){battleId=null;await widget.onResult();}}catch(e){setState(()=>status='$e');}finally{setState(()=>busy=false);}}
 @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[Text('Boss battle',style:Theme.of(c).textTheme.headlineSmall),DropdownButton<int>(value:topicId,hint:const Text('Choose topic'),items:widget.topics.map((t)=>DropdownMenuItem<int>(value:t['id'],child:Text('${t['name']} (${t['attempts']} attempts)'))).toList(),onChanged:(v)=>setState(()=>topicId=v)),if(battleId==null)FilledButton(onPressed:busy?null:start,child:const Text('Start boss')),if(battleId!=null)...[LinearProgressIndicator(value:hp/100),Text('${hp.toStringAsFixed(0)} / 100 HP'),const SizedBox(height:12),FilledButton(onPressed:busy?null:turn,child:const Text('Generate turn')),if(problem!=null)...[Text(problem!['prompt']),TextField(controller:answer,decoration:const InputDecoration(labelText:'Answer')),FilledButton(onPressed:busy?null:attack,child:const Text('Attack'))]],if(status.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:Text(status))]);}
class _Shop extends StatefulWidget { const _Shop({required this.api,required this.userId,required this.onResult}); final ApiClient api;final String userId;final Future<void> Function() onResult; @override State<_Shop> createState()=>_ShopState(); }
class _ShopState extends State<_Shop> {List<dynamic> items=[];bool busy=false;@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await widget.api.cosmetics(widget.userId);setState(()=>items=r);}catch(_){}}Future<void> buy(int id)async{setState(()=>busy=true);try{await widget.api.buyCosmetic(id,widget.userId);await load();await widget.onResult();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{setState(()=>busy=false);}}@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[Text('Cosmetics',style:Theme.of(c).textTheme.headlineSmall),if(items.isEmpty)const Text('No cosmetics seeded yet.'),...items.map((x)=>Card(child:ListTile(title:Text(x['name']),subtitle:Text('${x['price']} coins'),trailing:x['owned']==true?const Text('Owned'):FilledButton(onPressed:busy?null:()=>buy(x['id']),child:const Text('Buy')))))]);}
class _KeyDialog extends StatefulWidget { const _KeyDialog({required this.config,required this.initial,required this.onSaved}); final AppConfig config;final String initial;final void Function(String) onSaved;@override State<_KeyDialog> createState()=>_KeyDialogState(); }
class _KeyDialogState extends State<_KeyDialog>{late String provider;final key=TextEditingController();@override void initState(){super.initState();provider=widget.initial;}@override Widget build(BuildContext c)=>AlertDialog(title:const Text('LLM API key'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButton<String>(value:provider,items:widget.config.providers.map((p)=>DropdownMenuItem(value:p,child:Text(p))).toList(),onChanged:(v)=>setState(()=>provider=v!)),TextField(controller:key,obscureText:true,decoration:const InputDecoration(hintText:'Stored only in secure storage'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()async{if(key.text.isNotEmpty)await SecureKeys.saveLlmApiKey(provider,key.text);widget.onSaved(provider);if(mounted)Navigator.pop(c);},child:const Text('Save'))]);}
